import { filmData, PersonInfo, PersonProfile } from '../types/film';
import personsJson from '../assets/persons.json';

/**
 * Helpers for resolving a credited person's name to their TMDb identity and
 * normalized biographical record.
 *
 * Two data sources back this:
 *  - each film's `personProfiles` map (name -> { tmdbId, profileUrl }), merged
 *    here into a single global index keyed by normalized name, and
 *  - `persons.json`, the per-id biographical store (bio, birthday, etc.).
 *
 * Both are generated by the sync script (`.github/scripts/sync_sheet_to_json.py`).
 */

/** Matches the normalization the sync script uses when keying personProfiles. */
export const normalizePersonName = (name: string | null | undefined): string =>
    (name ?? '').trim().toLowerCase();

const personsById = personsJson as Record<string, PersonInfo>;

// Global name -> profile index, merged across every film. First non-null
// profile image for a given name wins, mirroring the sync script's merge.
const personIndexByName: Map<string, PersonProfile> = (() => {
    const index = new Map<string, PersonProfile>();
    for (const film of filmData) {
        const profiles = film.personProfiles;
        if (!profiles) continue;
        for (const [key, profile] of Object.entries(profiles)) {
            const existing = index.get(key);
            if (!existing) {
                index.set(key, profile);
            } else if (!existing.profileUrl && profile.profileUrl) {
                index.set(key, { ...existing, profileUrl: profile.profileUrl });
            }
        }
    }
    return index;
})();

/** Resolve a displayed name to its TMDb profile (id + per-film headshot), if known. */
export const getPersonProfileByName = (name: string | null | undefined): PersonProfile | undefined =>
    personIndexByName.get(normalizePersonName(name));

/** Look up the normalized biographical record for a TMDb person id. */
export const getPersonInfo = (tmdbId: number | null | undefined): PersonInfo | undefined =>
    tmdbId == null ? undefined : personsById[String(tmdbId)];

/** Convenience: resolve a name straight through to its biographical record. */
export const getPersonInfoByName = (name: string | null | undefined): PersonInfo | undefined =>
    getPersonInfo(getPersonProfileByName(name)?.tmdbId);

/** Public TMDb profile page for a person. */
export const tmdbPersonUrl = (tmdbId: number): string =>
    `https://www.themoviedb.org/person/${tmdbId}`;

/**
 * Whether a credited name should render as a clickable link. True when we can
 * resolve a TMDb id for them (so the modal has something to show) or they appear
 * in more than one club film (the original behavior, preserved as a floor).
 */
export const isPersonClickable = (
    name: string | null | undefined,
    filmographyLength: number,
): boolean => filmographyLength > 1 || getPersonProfileByName(name) !== undefined;

/**
 * Color/underline classes for a clickable credited name. Repeat club
 * contributors (people credited on 2+ of our films) get a distinct amber,
 * dotted-underline treatment so they stand out from one-off names that are
 * merely TMDb-resolvable (plain blue). Layout/focus classes are composed at the
 * call site so this stays reusable across the inline credits and the cast strip.
 */
export const personLinkClasses = (isRepeat: boolean): string =>
    isRepeat
        ? 'text-amber-300 hover:text-amber-200 underline decoration-dotted decoration-amber-400/70 underline-offset-2 font-medium'
        : 'text-blue-400 hover:text-blue-300 underline';
