name: Deploy to GitHub Pages

on:
  # Runs on manual trigger
  workflow_dispatch:
  
  # Deploy when specific files are changed
  push:
    branches:
      - main
    paths:
      - 'src/assets/club.json'
      - 'src/assets/films.json'
      - 'public/images/**'

# Fix for permission issue - changed to write
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step 2: Validate JSON files
      - name: Validate JSON files
        run: |
          # Check if club.json is valid
          if [ -f "src/assets/club.json" ]; then
            echo "Validating club.json..."
            if ! jq empty src/assets/club.json; then
              echo "ERROR: club.json is not valid JSON"
              exit 1
            fi
            echo "club.json is valid"
          fi
          
          # Check if films.json is valid
          if [ -f "src/assets/films.json" ]; then
            echo "Validating films.json..."
            if ! jq empty src/assets/films.json; then
              echo "ERROR: films.json is not valid JSON"
              exit 1
            fi
            echo "films.json is valid"
          fi
      
      # Step 3: Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      # Step 4: Install dependencies
      - name: Install dependencies
        run: bun install
      
      # Step 5: Build the project
      - name: Build the project
        run: bun run build
      
      # Step 6: Verify build output
      - name: Verify build output
        run: |
          echo "Checking build output directory..."
          ls -la
          if [ -d "dist" ]; then
            echo "dist directory exists"
            ls -la dist
          else
            echo "ERROR: dist directory does not exist"
            exit 1
          fi
      
      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages