name: Deploy to GitHub Pages

on:
  # Runs on manual trigger
  workflow_dispatch:
  
  # uncomment to deploy on push to main
  # push:
  #   branches:
  #     - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step 2: Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: bun install
      
      # Step 4: Build the project
      - name: Build the project
        run: bun run build
      
      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: # custom domain