name: Sync Google Sheet to JSON

on:
  schedule:
    # Run at 2pm CT (7pm UTC during CDT)
    - cron: '0 19 * * *'
    # Run at 10pm CT (3am UTC next day during CDT)
    - cron: '0 3 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run sync script
        run: python .github/scripts/sync_sheet_to_json.py
        env:
          SHEET_ID: "1wGrX2xWrJlS6WFpNxzD73VrHW4ZnrfedjtK5C9EYeuw"
          JSON_PATH: "src/assets/films.json"

      - name: Commit and push if changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/assets/films.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update films.json from Google Sheet" && git push)